### ISSUE TITLE
Sourcemaps wildcard matching seems to be broken

### ISSUE THREAD

**Issue by jzavisek** [bugsnag/webpack-bugsnag-plugins#41]
It seems that Bugsnag dashboard is unable to load sourcemaps files for wildcard URLs. I use this configuration:
```
new BugsnagSourceMapUploaderPlugin({
  apiKey: process.env.BUGSNAG_CLIENT_API_KEY,
  overwrite: true,
  publicPath: "https://*.--hidden--.co/_next/"
}),
```

These are the results:
![bugsnag-issue](https://user-images.githubusercontent.com/10927324/71001815-5fc81c80-20de-11ea-97c6-c2739285837c.png)

Dashboard doesn't match source map file to the error. Any ideas?

**Comment by phillipsam** [comment]
Hi @jzavisek - what is the application version reported on your error? This is displayed on the 'App' tab of your error event.

**Comment by jzavisek** [comment]
Hello @phillipsam Do you mean this?

![image](https://user-images.githubusercontent.com/10927324/71005689-678abf80-20e4-11ea-8404-a3476cfe3e1b.png)

**Comment by phillipsam** [comment]
@jzavisek yea
You will need to set the application version in your app:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#appversion

The source map will only be applied if the url and app version reported by the error event match the url and app version for the uploaded source map. Since your source map has a version of `3.30.0`, you will need your error event to report the same.

**Comment by jzavisek** [comment]
I see, that makes sense. Thanks for the clarification @phillipsam.

**Comment by phillipsam** [comment]
@jzavisek  No problem. Closing for now, but let us know if you have further issues!
