### ISSUE TITLE
rush rebuild/build will return 1 instead of 0 although uploading source map successfully

### ISSUE THREAD

**Issue by cqcmdwym** [bugsnag/webpack-bugsnag-plugins#65]
### Describe the bug
Rush build/rebuild command which will trigger webpack build to uploading source map, although uploading successfully but command return 1 instead of 0.
Run webpack command directly, everything is ok.

### Environment
* Node version: 12.16.1
* NPM version: 6.13.4
* Webpack version: 4

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```
==[ SUCCESS WITH WARNINGS: 1 project ]=========================================

--[ WARNING: xxxxxxxx ]-------------------------[ 54.61 seconds ]--

<i> [BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/x"


Projects succeeded with warnings.

```
</details>

**Comment by cqcmdwym** [comment]
@xander-jones thanks for your reply, looks like a rush bug, once I set
```
infrastructureLogging: {
    level: 'none' // disable logging due to rush tool issue
  }
```
rush build return exit code 0 instead of 1.

**Comment by xander-jones** [comment]
Thanks for letting us know, although this may just mask the issue, and possibly hide other problems should they occur. If it's just a temporary workaround that should be okay.

Will close this out as it doesn't appear to be due to the Bugsnag plugin, but let us know if you encounter any issues with our library, and we'll investigate 👍
